### ISSUE TITLE
feat: add hardhat scripts for benchmarking the gas consumption 

### ISSUE THREAD

**Issue by 0xsudo-eth** [chiru-labs/ERC721A#104] opened 2022-02-14 11:49 UTC
adding scripts to calculate the gas for ERC721A use cases should be beneficial for the project long term roadmap.

with scripts as a source of truth, we would be able to track and check the gas for multiple cases ( mint, transfer..etc) 

if the community agree on using hardhat script as gas estimation i can add those scripts

**Comment by fulldecent** [comment] 2022-02-14 21:09
Duplicate of #83

**Closed** 2022-02-21 19:51 UTC
