### ISSUE TITLE
Possible to use custom TokenURI for each token mapping?

### ISSUE THREAD

**Issue by LogeswaranA** [chiru-labs/ERC721A#146] opened 2022-03-01 17:43 UTC
I want to set tokenURI for each tokenbatch. Would that be possible here?. If yes, can you please direct?.. I could see the currentIndex to track the tokenId, but how do I set this tokenURI for the respective TokenBatch.

For instance, 1-10 => one tokenURI
11 => Another uri
12.- 15 => different tokenURI

Any thoughts?

**Comment by EmanuelCampos** [comment] 2022-03-01 18:18
A suggestion is to do it using a custom baseURI example:

```
string private baseURI1
string private baseURI2
string private baseURI3
```

so in the tokenURI you can check the tokenId and get the custom baseURI

```
    function tokenURI(uint256 tokenId) public view virtual override returns (string memory) {
        require(_exists(tokenId), "ERC721Metadata: URI query for nonexistent token");

        string memory baseURI = _baseURI();
        return bytes(baseURI).length > 0 ? string(abi.encodePacked(baseURI, tokenId.toString())) : "";
    }
```

**Comment by EmanuelCampos** [comment] 2022-03-01 18:22
A suggestion is to do it using a custom baseURI example:

```js
string private baseURI1
string private baseURI2
string private baseURI3
```

so in the tokenURI you can check the tokenId and get the custom baseURI

```js
    function tokenURI(uint256 tokenId) public view virtual override returns (string memory) {
        require(_exists(tokenId), "ERC721Metadata: URI query for nonexistent token");

        string memory baseURI;
        
        if(tokenId <= 10) {
            baseURI = _baseURI1();
        } else if(tokenId > 10) {
            baseURI = _baseURI2();
        }

        return bytes(baseURI).length > 0 ? string(abi.encodePacked(baseURI, tokenId.toString())) : "";
    }
```

**Comment by ahbanavi** [comment] 2022-03-02 07:03
Duplicate of #122

**Closed** 2022-03-12 13:13 UTC
