### ISSUE TITLE
Gas fees very high on safeTransfer Method

### ISSUE THREAD

**Issue by dilukangelosl** [chiru-labs/ERC721A#145] opened 2022-03-01 08:50 UTC
I minted 310 tokens at a single transaction.  
Eg: 0 to 310 

Safetransfering Token ID is around $8
Safetransfering Token ID 300 is around $300

Wonder whats caused the price change for high index tokens. 

This only happens for higher transactions

**Comment by ahbanavi** [comment] 2022-03-01 10:09
When you are transferring a token, contract checks the owner of the token using [ownershipOf](https://github.com/chiru-labs/ERC721A/blob/8e836e5db90c791702b1a6358a20edbb1fb1b8af/contracts/ERC721A.sol#L188-L213) function.  
This function may run a loop and that's cost SLOAD for each iteration, and when batch size is high (like 310) and you want to transfer 300th token, the loop iterate from 300 to 0 and that cost 300 SLOADs.  
https://github.com/chiru-labs/ERC721A/blob/8e836e5db90c791702b1a6358a20edbb1fb1b8af/contracts/ERC721A.sol#L202-L208

You could use small batch size like 5 or 10.
Also see #83 and [this tweet](https://twitter.com/fulldecent/status/1491506119486885895?s=20&t=u5MU9jNa5Gwy697I1_ipMw).

**Comment by EmanuelCampos** [comment] 2022-03-01 13:12
> ERC721A/contracts/ERC721A.sol

Could 

> When you are transferring a token, contract checks the owner of the token using [ownershipOf](https://github.com/chiru-labs/ERC721A/blob/8e836e5db90c791702b1a6358a20edbb1fb1b8af/contracts/ERC721A.sol#L188-L213) function. This function may run a loop and that's cost SLOAD for each iteration, and when batch size is high (like 310) and you want to transfer 300th token, the loop iterate from 300 to 0 and that cost 300 SLOADs.
> 
> https://github.com/chiru-labs/ERC721A/blob/8e836e5db90c791702b1a6358a20edbb1fb1b8af/contracts/ERC721A.sol#L202-L208
> 
> You could use small batch size like 5 or 10. Also see #83 and [this tweet](https://twitter.com/fulldecent/status/1491506119486885895?s=20&t=u5MU9jNa5Gwy697I1_ipMw).

Could you explain better about use small batch size? it's abbout small batch in mint? so the transfer will be more cheaper?

**Comment by ahbanavi** [comment] 2022-03-01 14:15
> Could you explain better about use small batch size? it's abbout small batch in mint? so the transfer will be more cheaper?  
  
Contracts can implement a `maxBatchSize` variable and limit the `quantity` that a minter can mint in a single transaction.  

```solidity
uint256 private constant maxBatchSize = 5;

function mint(quantity) external payable {
    require(quantity <= maxBatchSize, "quantity to mint too high");
    .
    .
    .
   _safeMint(msg.sender, quantity);
}
```

By setting a small `maxBatchSize`, you are also limiting the maximum iteration of the loop inside `ownershipOf`.  
Therefore, the maximum gas that this function costs would be lower.    
In other words, the `ownershipOf` functions became `O(maxBatchSize)`.

**Comment by Vectorized** [comment] 2022-03-01 14:58
Just transfer from lower id to upper id. 

This is actually an anti-dumping feature. Working as intended.

**Comment by Vectorized** [comment] 2022-06-06 07:00
Closing this, as users have several options to reduce the first-time transfer gas usage to reasonable levels. 

Please refer to the documentation for tips.

**Closed by Vectorized** 2022-06-06 07:00 UTC

**Comment by basememara** [comment] 2022-07-28 23:55
I minted 5000 NFTs at once, which doesn't seem like the intended use of this contract.. I'm supposed to batch them in groups of 8? Since I batch minted them all, transferring token 1 is about $10 while transferring token 4000 is $700-800. Any ideas or insights on how to fix my scenario?

**Comment by Vectorized** [comment] 2022-07-29 00:41
What you can do is to batch transfer every 10th NFT to some wallet you own. (1,11,21,…4991)

You can use some tool like https://nft.life/batch-transfer. Do call setApprovalForAll first to approve the batch transfer contract to transfer your NFTs.
